name: Update WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: "true"
          BLOCKS: "⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿"
          TIME_RANGE: "last_7_days"
          LANG_COUNT: 5
          SHOW_TIME: "true"
          SHOW_BAR: "true"
          SHOW_TOTAL: "false"
